[package]
name = "duet-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gpui = { workspace = true }
duet-types = { path = "../duet-types" }
duet-vfs = { path = "../duet-vfs" }
duet-index = { path = "../duet-index" }
duet-config = { path = "../duet-config" }
duet-widgets = { path = "../duet-widgets" }
duet-ops = { path = "../duet-ops" }
duet-platform = { path = "../duet-platform" }
tokio = { workspace = true }
