[package]
name = "duet-vfs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
duet-types = { path = "../duet-types" }
duet-platform = { path = "../duet-platform" }
futures = { workspace = true }
async-trait = { workspace = true }
libc = { workspace = true }
rustix = { workspace = true }
log = { workspace = true }
tokio-stream = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
tempfile = { workspace = true }

[[bench]]
name = "dir_enumeration"
harness = false
