//! Stub Plugin Implementation
//!
//! Demonstrates full implementation of all 5 Duet plugin interfaces:
//! - Content (WDX): Custom columns & metadata
//! - Packer (WCX): Archive formats
//! - Filesystem (WFX): Virtual/remote file systems
//! - Viewer (WLX): File preview rendering
//! - Command: Action palette and keyboard commands

wit_bindgen::generate!({
    world: "duet-plugin",
    path: "../../wit",
});

use exports::duet::plugin::{
    command_plugin::{CommandInfo, Guest as CommandGuest, SelectionContext},
    content_plugin::{FieldDef, FieldType, FieldValue, Guest as ContentGuest},
    fs_plugin::Guest as FsGuest,
    packer_plugin::Guest as PackerGuest,
    viewer_plugin::{CanvasData, Guest as ViewerGuest, RenderTarget},
};
use duet::plugin::host::{self, Entry, Error, ErrorCode, LogLevel};

struct StubPlugin;

impl ContentGuest for StubPlugin {
    fn fields() -> Vec<FieldDef> {
        vec![FieldDef {
            name: "stub_column".to_string(),
            field_type: FieldType::StringType,
            description: "A stub column provided by duet-stub-plugin".to_string(),
            readonly: true,
        }]
    }

    fn value(
        path: String,
        field: u32,
        _handle: Option<u32>,
    ) -> Result<FieldValue, Error> {
        host::log(LogLevel::Info, &format!("Content plugin value requested for path: {}", path));
        if field == 0 {
            Ok(FieldValue::ValString(format!("Stub metadata for {}", path)))
        } else {
            Err(Error {
                code: ErrorCode::InvalidInput,
                message: format!("Unknown field index: {}", field),
            })
        }
    }
}

impl PackerGuest for StubPlugin {
    fn probe(head: Vec<u8>, name: String) -> bool {
        name.ends_with(".stub") || head.starts_with(b"STUB")
    }

    fn list(_archive: u32) -> Result<Vec<Entry>, Error> {
        Ok(vec![Entry {
            name: "stub_entry.txt".to_string(),
            size: 1024,
            mtime: 1700000000,
            mode: 0o644,
            is_dir: false,
        }])
    }

    fn extract(_archive: u32, member: String, _out: u32) -> Result<(), Error> {
        host::log(LogLevel::Info, &format!("Extracting member: {}", member));
        Ok(())
    }

    fn can_write() -> bool {
        false
    }

    fn add(_archive: u32, _member: String, _src: u32) -> Result<(), Error> {
        Err(Error {
            code: ErrorCode::NotSupported,
            message: "Packer write not supported in stub plugin".to_string(),
        })
    }
}

impl FsGuest for StubPlugin {
    fn connect(location: String) -> Result<u32, Error> {
        host::log(LogLevel::Info, &format!("Connecting to FS location: {}", location));
        Ok(1) // Return session handle 1
    }

    fn list(_session: u32, path: String) -> Result<Vec<Entry>, Error> {
        Ok(vec![Entry {
            name: format!("file_in_{}.txt", path.trim_matches('/')),
            size: 2048,
            mtime: 1700000000,
            mode: 0o644,
            is_dir: false,
        }])
    }

    fn get(_session: u32, _src_path: String, _dest_handle: u32) -> Result<(), Error> {
        Ok(())
    }

    fn put(_session: u32, _src_handle: u32, _dest_path: String) -> Result<(), Error> {
        Err(Error {
            code: ErrorCode::NotSupported,
            message: "Put operation not supported in stub plugin".to_string(),
        })
    }

    fn remove(_session: u32, _path: String, _is_dir: bool) -> Result<(), Error> {
        Err(Error {
            code: ErrorCode::PermissionDenied,
            message: "Remove disabled in stub plugin".to_string(),
        })
    }

    fn mkdir(_session: u32, _path: String) -> Result<(), Error> {
        Ok(())
    }

    fn rename(_session: u32, _old_path: String, _new_path: String) -> Result<(), Error> {
        Ok(())
    }
}

impl ViewerGuest for StubPlugin {
    fn probe(head: Vec<u8>, extension: String) -> bool {
        extension == "stub" || head.starts_with(b"STUB")
    }

    fn render_to_markdown(_handle: u32) -> Result<String, Error> {
        Ok("# Stub Plugin Preview\n\nThis is a markdown preview generated by `duet-stub-plugin`.".to_string())
    }

    fn render_to_text(_handle: u32) -> Result<String, Error> {
        Ok("Stub Plugin Text Preview".to_string())
    }

    fn render_to_canvas(_handle: u32, max_width: u32, max_height: u32) -> Result<CanvasData, Error> {
        Ok(CanvasData {
            width: max_width.min(100),
            height: max_height.min(100),
            pixels: vec![255; (max_width.min(100) * max_height.min(100) * 4) as usize],
        })
    }

    fn render(handle: u32) -> Result<RenderTarget, Error> {
        let md = Self::render_to_markdown(handle)?;
        Ok(RenderTarget::Markdown(md))
    }
}

impl CommandGuest for StubPlugin {
    fn register_commands() -> Vec<CommandInfo> {
        vec![CommandInfo {
            id: "stub.hello".to_string(),
            title: "Stub: Say Hello".to_string(),
            description: "Demonstration command from stub plugin".to_string(),
            shortcut: Some("Ctrl+Shift+H".to_string()),
        }]
    }

    fn invoke(command_id: String, ctx: SelectionContext) -> Result<(), Error> {
        host::log(
            LogLevel::Info,
            &format!("Invoked command '{}' with active panel: {}", command_id, ctx.active_panel_path),
        );
        Ok(())
    }
}

export!(StubPlugin);
